export const ADD_REMINDER = 'ADD_REMINDER';
export const CHANGE_SELECTED_DAY = 'CHANGE_SELECTED_DAY';
export const HIDE_MODAL = 'HIDE_MODAL';
export const SHOW_MODAL_ADD_FORM = 'SHOW_MODAL_ADD_FORM';
export const EDIT_REMINDER = 'EDIT_REMINDER';